import type { TFunction } from 'i18next';
import type { InstanceStatus } from '../../../services/instanceService';

export type CreateMode = 'clone-default' | 'new';
export type CloneMode = 'full' | 'profile';

export interface InstanceSelectorApi {
    t: TFunction;
    instances: InstanceStatus[];
    activeInstance?: InstanceStatus;
    activeInstanceId?: string | null;
    fastForwardShortcut: string;
    isOpen: boolean;
    setIsOpen: (v: boolean) => void;
    searchQuery: string;
    setSearchQuery: (v: string) => void;
    isCreateOpen: boolean;
    setIsCreateOpen: (v: boolean) => void;
    isCopyOpen: boolean;
    setIsCopyOpen: (v: boolean) => void;
    isEditOpen: boolean;
    setIsEditOpen: (v: boolean) => void;
    isDeleteOpen: boolean;
    setIsDeleteOpen: (v: boolean) => void;
    newInstanceName: string;
    setNewInstanceName: (v: string) => void;
    createMode: CreateMode;
    setCreateMode: (v: CreateMode) => void;
    copyInstanceName: string;
    setCopyInstanceName: (v: string) => void;
    copyTargetId: string | null;
    setCopyTargetId: (v: string | null) => void;
    cloneMode: CloneMode;
    setCloneMode: (v: CloneMode) => void;
    copyProjects: boolean;
    setCopyProjects: (v: boolean) => void;
    editInstanceName: string;
    setEditInstanceName: (v: string) => void;
    editTargetId: string | null;
    launchingId: string | null;
    isRotating: boolean;
    isIoOpen: boolean;
    setIsIoOpen: (v: boolean) => void;
    deleteTarget: InstanceStatus | null;
    dropdownRef: React.RefObject<HTMLDivElement | null>;
    fileInputRef: React.RefObject<HTMLInputElement | null>;
    activeItemRef: React.RefObject<HTMLDivElement | null>;
    filteredInstances: InstanceStatus[];
    handleCreate: () => Promise<void>;
    handleCopy: () => Promise<void>;
    handleSetDefault: (targetId: string) => Promise<void>;
    handleEdit: () => Promise<void>;
    handleDelete: () => Promise<void>;
    handleSmartPlay: (targetId?: string) => Promise<void>;
    handleToggleLaunch: (instanceId: string, isRunning: boolean) => Promise<void>;
    handleExportProfiles: () => Promise<void>;
    handleImportProfiles: () => Promise<void>;
    handleFileInput: (e: React.ChangeEvent<HTMLInputElement>) => Promise<void>;
    handleSmartRotate: (sourceId?: string) => Promise<void>;
    openCreate: () => void;
    openCopy: (targetId: string, name: string) => void;
    openEdit: (targetId: string, name: string) => void;
    openDelete: (target: InstanceStatus) => void;
    handleSelectInstance: (instId: string, seqNum: number, name: string) => Promise<void>;
    closeDelete: () => void;
}
