use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::{env, fs, path::PathBuf, time::Duration};
use tokio::process::Command;

mod acquire_openclaw_config_lock;
mod sync_openclaw_provider;

pub(crate) use acquire_openclaw_config_lock::acquire_openclaw_config_lock;
pub(crate) use acquire_openclaw_config_lock::atomically_write_config;
pub use acquire_openclaw_config_lock::check_openclaw_installed;
pub use acquire_openclaw_config_lock::classify_openclaw_version;
pub(crate) use acquire_openclaw_config_lock::create_backup;
pub(crate) use acquire_openclaw_config_lock::extract_version;
pub(crate) use acquire_openclaw_config_lock::find_in_path;
pub(crate) use acquire_openclaw_config_lock::get_backup_path;
pub(crate) use acquire_openclaw_config_lock::get_config_path;
pub(crate) use acquire_openclaw_config_lock::get_openclaw_dir;
pub(crate) use acquire_openclaw_config_lock::is_managed_provider;
pub(crate) use acquire_openclaw_config_lock::is_valid_version;
pub(crate) use acquire_openclaw_config_lock::normalize_base_url;
pub(crate) use acquire_openclaw_config_lock::read_openclaw_config;
pub(crate) use acquire_openclaw_config_lock::redact_json_value;
pub use acquire_openclaw_config_lock::resolve_model_specs;
pub(crate) use acquire_openclaw_config_lock::resolve_openclaw_path;
pub(crate) use acquire_openclaw_config_lock::run_openclaw_version;
pub(crate) use acquire_openclaw_config_lock::run_version_command;
pub use acquire_openclaw_config_lock::OpenClawStatus;
pub(crate) use acquire_openclaw_config_lock::PROVIDER_ID;
pub use sync_openclaw_provider::clear_openclaw_config;
pub use sync_openclaw_provider::execute_openclaw_clear;
pub use sync_openclaw_provider::execute_openclaw_restore;
pub use sync_openclaw_provider::execute_openclaw_sync;
pub use sync_openclaw_provider::get_openclaw_config_content;
pub use sync_openclaw_provider::get_openclaw_sync_status;
pub use sync_openclaw_provider::read_openclaw_config_content;
pub use sync_openclaw_provider::restore_openclaw_config;
pub use sync_openclaw_provider::sync_openclaw_provider;
#[cfg(test)]
pub(crate) use sync_openclaw_provider::tests;
