use super::*;
use serde_json::json;

#[test]
fn test_restore_and_finalize_gemini_contents_with_model_claude_target_rejects_gemini_signature() {
    let store = ThinkingStore::new();
    let key = "t:cross_model_test_session";
    let gemini_sig = "Ep4KCpsKAWkUfRMa5ZYMDdlPjxrQTLzVZ6MZeopI88888888888888888888888888888888";

    // 模拟上一轮 Gemini 存储的思考记录（带有 Gemini 原生签名）
    store.record(
        key,
        ThinkingRecord {
            fingerprint: "fp_test_cross".to_string(),
            thought: "Thought generated by Gemini".to_string(),
            signature: Some(gemini_sig.to_string()),
            tool_ids: vec![],
            tool_names: vec![],
            visible: "Gemini visible text".to_string(),
        },
    );

    // 客户端在同一 session 下切换模型为 Claude 发起后续对话
    let mut contents = vec![
        json!({ "role": "user", "parts": [{ "text": "Hello" }] }),
        json!({
            "role": "model",
            "parts": [{ "text": "Gemini visible text" }]
        }),
        json!({ "role": "user", "parts": [{ "text": "Next turn" }] }),
    ];

    // 1. 执行 restore（针对目标模型 claude-opus-4-6-thinking）
    let restored = store.restore_gemini_contents_with_model(
        key,
        &mut contents,
        Some("claude-opus-4-6-thinking"),
    );
    assert_eq!(restored, 1);

    // 恢复出的 thinking 块绝不能挂载 Gemini 签名！
    let parts_after_restore = contents[1]["parts"].as_array().unwrap();
    assert!(
        parts_after_restore[0].get("thoughtSignature").is_none(),
        "ThinkingStore must not assign foreign Gemini signature when target is Claude"
    );

    // 2. 执行 finalize（终审节点）
    finalize_gemini_contents_thinking_with_model(
        &mut contents,
        true,
        Some("claude-opus-4-6-thinking"),
    );

    // 终审把关：没有合法 Claude 签名的思考块安全降级为普通 text，绝不报 400 签名错误
    let final_parts = contents[1]["parts"].as_array().unwrap();
    let has_thought_block = final_parts
        .iter()
        .any(|p| p.get("thought").and_then(|v| v.as_bool()) == Some(true));
    assert!(
        !has_thought_block,
        "Claude turn must NOT have thought: true when thinking lacked a genuine Claude signature"
    );
    assert!(
        final_parts
            .iter()
            .any(|p| p.get("text").and_then(|t| t.as_str()) == Some("Thought generated by Gemini")),
        "Original thinking content must be safely preserved as text in conversation history"
    );
}

#[test]
fn test_finalize_thinking_disabled_preserves_historical_thinking_and_signatures() {
    let real_sig = "Ep4MCpsMARFNMg9NDlK9RXXz5Mzq9mniX9KSQBBzbUx3k85w/qDgtcE+28NH+1EvPeULAprqUquvYXGMzUXGy1xJoMnqdkC4vqebuhyd2Xhs0oz+OhqcOTwLhGYOG0KBKQ87Hfw4q/sMCSgf2gz4vFMa6V6kKMJepYlPXKFJJF4ok+W6lUt3PfYln8K9Dh7wB/40iHiZ2BnJd++6hfUwu9Bz1n795S50l0yCj84EaSCDDF334Erxq7Fo";
    // 模拟多轮对话：
    // Turn 1: User
    // Turn 2: Model (历史已发生，包含合法思考块与工具调用及签名)
    // Turn 3: User (工具返回)
    // Turn 4: User (最新一轮用户提问，并且在这一轮用户把思考开关关闭了)
    let mut contents = vec![
        json!({
            "role": "user",
            "parts": [{ "text": "Run bash command" }]
        }),
        json!({
            "role": "model",
            "parts": [
                {
                    "text": "Planning to run ls...",
                    "thought": true
                },
                {
                    "functionCall": {
                        "name": "bash",
                        "args": { "command": "ls" }
                    },
                    "thoughtSignature": real_sig
                }
            ]
        }),
        json!({
            "role": "user",
            "parts": [{
                "functionResponse": {
                    "name": "bash",
                    "response": { "output": "file1.txt" }
                }
            }]
        }),
        json!({
            "role": "user",
            "parts": [{ "text": "Now answer without thinking" }]
        }),
    ];

    // 最新一轮关思考 (is_thinking_enabled = false)
    finalize_gemini_contents_thinking_with_model(
        &mut contents,
        false,
        Some("gemini-3.8-flash-tiered"),
    );

    // 验证历史 Turn 2 的思考块与工具调用签名是否被完好保留：
    let history_model_parts = contents[1]["parts"].as_array().expect("parts array");
    assert_eq!(history_model_parts.len(), 2);
    assert_eq!(history_model_parts[0]["text"], "Planning to run ls...");
    assert_eq!(history_model_parts[1]["thoughtSignature"], real_sig, "Historical tool thoughtSignature must NOT be stripped when thinking is disabled in the current turn");
}

#[test]
fn test_finalize_thinking_disabled_keeps_unsigned_function_call_unsigned_for_gemini() {
    let mut contents = vec![json!({
        "role": "model",
        "parts": [
            {
                "functionCall": {
                    "name": "grep",
                    "id": "call_unsigned",
                    "args": { "pattern": "abc" }
                }
            }
        ]
    })];

    // 关思考出站，发往 Gemini
    finalize_gemini_contents_thinking_with_model(
        &mut contents,
        false,
        Some("gemini-3.8-flash-tiered"),
    );

    // 官方报文里哨兵出现 0 次；缺失签名被上游容忍（在飞轮即缺席）。
    // 因此无签名的 functionCall 保持「字段缺席」，绝不发明占位符。
    let parts = contents[0]["parts"].as_array().unwrap();
    assert_eq!(parts.len(), 1);
    assert!(
        parts[0].get("thoughtSignature").is_none() && parts[0].get("thought_signature").is_none(),
        "Unsigned functionCall must stay unsigned when sent to Gemini — never invent a sentinel"
    );
}

#[test]
fn test_finalize_does_not_invent_signature_for_unsigned_function_call() {
    let tool_id = "call_finalize_cache_777";
    let mut contents = vec![json!({
        "role": "model",
        "parts": [
            {
                "functionCall": {
                    "name": "run_command",
                    "id": tool_id,
                    "args": { "cmd": "cargo test" }
                }
                // 注意：未带 thoughtSignature（模拟未在进站流水线查到的工具调用）
            }
        ]
    })];

    // 终审出站，发往 Gemini
    finalize_gemini_contents_thinking_with_model(
        &mut contents,
        true,
        Some("gemini-3.8-flash-tiered"),
    );

    let parts = contents[0]["parts"].as_array().unwrap();
    // 终审门禁：不查库、不发明签名。官方 functionCall 轮是"纯净"的
    // （33 个 model 轮里 thought × functionCall 共现 0 次），因此不得注入占位思考块。
    assert_eq!(
        parts.len(),
        1,
        "finalize must NOT inject a placeholder thought block"
    );
    let fc = parts
        .iter()
        .find(|p| p.get("functionCall").is_some())
        .unwrap();
    assert!(
        fc.get("thoughtSignature").is_none(),
        "Pipeline finalize must not invent a sentinel; absence is tolerated by upstream"
    );
}

#[test]
fn test_finalize_thinking_disabled_strips_tool_signature_for_claude() {
    let real_sig = "s".repeat(60);
    let mut contents = vec![json!({
        "role": "model",
        "parts": [
            {
                "functionCall": {
                    "name": "grep",
                    "id": "call_123",
                    "args": {}
                },
                "thoughtSignature": real_sig
            }
        ]
    })];

    // 关思考出站，发往 Claude
    finalize_gemini_contents_thinking_with_model(&mut contents, false, Some("claude-3-7-sonnet"));

    let parts = contents[0]["parts"].as_array().unwrap();
    assert_eq!(parts.len(), 1);
    assert!(
        parts[0].get("thoughtSignature").is_none(),
        "Tool call thoughtSignature must be stripped for Claude models"
    );
}

#[test]
fn test_restore_deduplicates_and_elevates_thought_from_plain_text() {
    let store = ThinkingStore::new();
    let key = "t:re-elevation-dedup-test";
    let tool_id = "call_dedup_001";
    let real_sig = "Ep4MCpsMARFNMg9NDlK9RXXz5Mzq9mniX9KSQBBzbUx3k85w/qDgtcE+28NH+1EvPeULAprqUquvYXGMzUXGy1xJoMnqdkC4vqebuhyd2Xhs0oz+OhqcOTwLhGYOG0KBKQ87Hfw4q/sMCSgf2gz4vFMa6V6kKMJepYlPXKFJJF4ok+W6lUt3PfYln8K9Dh7wB/40iHiZ2BnJd++6hfUwu9Bz1n795S50l0yCj84EaSCDDF334Erxq7Fo";
    let thought_text = "I am analyzing the repository carefully and formulating a search query.";
    let visible_answer = "Here is the exact file path you requested.";

    // 1. 模拟旧轮次入库（开思考时发生的思维记录）
    // Justification: best-effort persistence/sync/notification; failure logged, in-memory state remains authoritative for this run
    crate::error::record_ignored(
        crate::modules::proxy_db::save_thinking_record(
            key,
            "fp_dedup_001",
            thought_text,
            Some(real_sig),
            &[tool_id.to_string()],
            &["grep".to_string()],
            visible_answer,
        ),
        "save_thinking_record",
    );

    // 2. 模拟客户端发上来的历史：之前关思考时降级的思考文本变成了普通正文部件，残留或与正文拼接在一起
    let mut contents = vec![
        json!({
            "role": "user",
            "parts": [{ "text": "Find the file" }]
        }),
        json!({
            "role": "model",
            "parts": [
                { "text": thought_text }, // 降级残留的普通文本部件
                { "text": visible_answer },
                {
                    "functionCall": {
                        "name": "grep",
                        "id": tool_id,
                        "args": {}
                    }
                }
            ]
        }),
        json!({
            "role": "user",
            "parts": [{ "functionResponse": { "name": "grep", "response": { "res": "ok" } } }]
        }),
    ];

    // 3. 当前轮次重新开启思考，执行复活与重提升
    let restored = store.restore_gemini_contents_with_model(
        key,
        &mut contents,
        Some("gemini-3.8-flash-tiered"),
    );
    assert_eq!(restored, 1, "Must restore exactly 1 turn");

    let model_parts = contents[1]["parts"].as_array().expect("parts array");
    // 验证：
    // 1. 首位成功提升恢复为真正的思考块 (thought: true)
    assert_eq!(model_parts[0]["thought"], true);
    assert_eq!(model_parts[0]["text"], thought_text);

    // 2. 正文部件中的降级残留部件被精准剔除，只保留真实的可见回答，消灭双份复读！
    assert_eq!(model_parts[1]["text"], visible_answer);
    assert!(model_parts[1].get("thought").is_none());

    // 3. 工具调用挂载真实签名
    assert_eq!(model_parts[2]["functionCall"]["id"], tool_id);
    assert_eq!(model_parts[2]["thoughtSignature"], real_sig);

    // Justification: best-effort persistence/sync/notification; failure logged, in-memory state remains authoritative for this run
    crate::error::record_ignored(
        crate::modules::proxy_db::delete_thinking_records_for_session(key),
        "delete_thinking_records_for_session",
    );
}

#[test]
fn test_gemini_to_claude_wraps_foreign_thought_in_think_tags_and_strips_tool_sig() {
    let gemini_sig = "Ep4MCpsMARFNMg9NDlK9RXXz5Mzq9mniX9KSQBBzbUx3k85w/qDgtcE+28NH+1EvPeULAprqUquvYXGMzUXGy1xJoMnqdkC4vqebuhyd2Xhs0oz+OhqcOTwLhGYOG0KBKQ87Hfw4q/sMCSgf2gz4vFMa6V6kKMJepYlPXKFJJF4ok+W6lUt3PfYln8K9Dh7wB/40iHiZ2BnJd++6hfUwu9Bz1n795S50l0yCj84EaSCDDF334Erxq7Fo";
    let thought_text = "Step 1: Check database schema. Step 2: Query tables.";
    let visible_answer = "Found 3 matching records in the database.";

    let mut contents = vec![json!({
        "role": "model",
        "parts": [
            {
                "text": thought_text,
                "thought": true,
                "thoughtSignature": gemini_sig
            },
            {
                "text": visible_answer
            },
            {
                "functionCall": {
                    "name": "query_db",
                    "id": "call_db_1",
                    "args": {}
                },
                "thoughtSignature": gemini_sig
            }
        ]
    })];

    // 目标模型切为 Claude
    finalize_gemini_contents_thinking_with_model(&mut contents, true, Some("claude-3-7-sonnet"));

    let parts = contents[0]["parts"].as_array().expect("parts array");
    // 1. Gemini 的思考块不具备 Claude 签名，因此绝不可作为 thought: true 上送 Claude
    assert!(parts
        .iter()
        .all(|p| p.get("thought").and_then(|v| v.as_bool()) != Some(true)));

    // 2. 思考文本被包装为 <think> 标签前置于正文部件
    let first_text = parts[0]["text"].as_str().expect("text");
    assert!(first_text.starts_with("<think>"));
    assert!(first_text.contains(thought_text));
    assert!(first_text.contains("</think>"));

    // 3. 正文回答完好保留
    assert_eq!(parts[1]["text"], visible_answer);

    // 4. 工具调用上的签名被彻底拔出
    assert_eq!(parts[2]["functionCall"]["id"], "call_db_1");
    assert!(parts[2].get("thoughtSignature").is_none());
    assert!(parts[2].get("thought_signature").is_none());
}

#[test]
fn test_extract_think_tags_helper() {
    let input = "<think>\nThinking line 1\nThinking line 2\n</think>\n\nFinal response text here.";
    let res = extract_think_tags(input);
    assert!(res.is_some());
    let (thought, visible) = res.unwrap();
    assert_eq!(thought, "Thinking line 1\nThinking line 2");
    assert_eq!(visible, "Final response text here.");

    // No tags
    assert!(extract_think_tags("Just normal text").is_none());
}

#[test]
fn test_gemini_native_synthetic_id_bridges_cross_protocol_signature_recovery() {
    let store = ThinkingStore::new();
    let key = "t:cross-proto-synthetic-id-test";
    let client_tool_id = "call_openai_native_456";
    let real_sig = "EmIKYAFpFH0TDqviLY1vZ8EuHqBLLj5xxD+0hchYg2VaoyolUQRP+hSCsKRpSpj+yrQA2H27yVFnF7tlp5OHIUvTdZKKErAqILJzK5FG8RJg42jCaaI2/iwqoBuRd5BDVwBxaQ==";
    let thought_text = "Analyzing directory and listing files.";
    let _visible_answer = "Running bash tool.";

    // 1. 模拟 OpenAI 协议下生成的工具调用（带有 client_tool_id）
    let mut acc = TurnAccumulator::with_anchor("user-root-anchor");
    acc.ingest_part(&json!({
        "thought": true,
        "text": thought_text,
        "thoughtSignature": real_sig
    }));
    acc.ingest_part(&json!({
        "functionCall": {
            "name": "bash",
            "args": { "command": "ls -la" },
            "id": client_tool_id
        },
        "thoughtSignature": real_sig
    }));
    acc.commit(key);

    // 2. 模拟用户切换到了原生 Gemini 协议发起后续对话：
    // 原生 Gemini 请求的 contents 中天生没有 id 字段（id: None）！
    let mut gemini_contents = vec![
        json!({
            "role": "user",
            "parts": [{ "text": "List the files" }]
        }),
        json!({
            "role": "model",
            "parts": [
                {
                    "functionCall": {
                        "name": "bash",
                        "args": { "command": "ls -la" }
                        // 注意：完全无 id 字段！
                    }
                }
            ]
        }),
        json!({
            "role": "user",
            "parts": [{ "functionResponse": { "name": "bash", "response": { "res": "file.txt" } } }]
        }),
    ];

    // 3. 原生 Gemini 协议执行流水线复活与终审出站
    let restored = store.restore_gemini_contents_with_model(
        key,
        &mut gemini_contents,
        Some("gemini-3.8-flash-tiered"),
    );
    assert_eq!(
        restored, 1,
        "Must match via synthetic context ID even though Gemini request had no tool id"
    );

    finalize_gemini_contents_thinking_with_model(
        &mut gemini_contents,
        true,
        Some("gemini-3.8-flash-tiered"),
    );

    let model_parts = gemini_contents[1]["parts"].as_array().expect("parts");
    // 验证思考块被成功提升复活：
    assert_eq!(model_parts[0]["thought"], true);
    assert_eq!(model_parts[0]["text"], thought_text);

    // 验证跨协议捕获到的真实签名被归位到锚点，而不是被替换成哨兵：
    let fc = &model_parts[1];
    assert_eq!(fc["functionCall"]["name"], "bash");
    assert_eq!(
        fc["thoughtSignature"], real_sig,
        "Captured real signature must be restored onto the anchor, not replaced by a sentinel"
    );
    // 验证伪 ID 纯粹内部使用，绝不外泄给无 ID 协议：
    assert!(
        fc["functionCall"].get("id").is_none(),
        "Synthetic ID must remain internal and not leak to client"
    );

    // Justification: best-effort persistence/sync/notification; failure logged, in-memory state remains authoritative for this run
    crate::error::record_ignored(
        crate::modules::proxy_db::delete_thinking_records_for_session(key),
        "delete_thinking_records_for_session",
    );
}
