import type { InstanceStatus, AutoSwitcherDaemonStatus } from '../../services/instanceService';
import type { AgmProjectTreeNode } from '../../components/instances/PromptTreeViewModal';
import type { InstanceActionType } from './instancePageUtils';
import type { TFunction } from 'i18next';
import type { Account } from '../../types/account';

export interface InstancePageApi {
    t: TFunction;
    instances: InstanceStatus[];
    activeInstanceId?: string | null;
    switcherStatus: unknown;
    isLoading: boolean;
    storeError: string | null;
    accounts: Account[];
    currentAccount: unknown;
    config: unknown;
    searchQuery: string;
    setSearchQuery: (v: string) => void;
    viewMode: 'card' | 'list';
    cardDensity: 'normal' | 'compact';
    filteredInstances: InstanceStatus[];
    runningCount: number;
    runningTreeNodes: AgmProjectTreeNode[];
    projectTreeNodes: AgmProjectTreeNode[];
    daemonStatus: AutoSwitcherDaemonStatus | null;
    daemonCountdown: number;
    actionError: string | null;
    setActionError: (v: string | null) => void;
    actionState: Record<string, InstanceActionType>;
    setActionState: React.Dispatch<React.SetStateAction<Record<string, InstanceActionType>>>;
    deletingId: string | null;
    isSyncingAll: boolean;
    syncingInstanceIds: Record<string, boolean>;
    activeCardRef: React.RefObject<HTMLDivElement | null>;
    cardMoreId: string | null;
    setCardMoreId: (v: string | null) => void;
    promptTreeInstance: { id: string; name: string; projectId?: string; seqNum?: number; executablePath?: string } | null;
    setPromptTreeInstance: (v: InstancePageApi['promptTreeInstance']) => void;
    isCreateOpen: boolean;
    setIsCreateOpen: (v: boolean) => void;
    newInstanceName: string;
    setNewInstanceName: (v: string) => void;
    newInstanceBoundAccount: string;
    setNewInstanceBoundAccount: (v: string) => void;
    newInstanceFromInstance: string;
    setNewInstanceFromInstance: (v: string) => void;
    newInstanceLaunchImmediately: boolean;
    setNewInstanceLaunchImmediately: (v: boolean) => void;
    switchTargetInstance: InstanceStatus | null;
    setSwitchTargetInstance: (v: InstanceStatus | null) => void;
    accountSearchQuery: string;
    setAccountSearchQuery: (v: string) => void;
    copyTargetId: string | null;
    setCopyTargetId: (v: string | null) => void;
    copyInstanceName: string;
    setCopyInstanceName: (v: string) => void;
    cloneMode: 'full' | 'profile';
    setCloneMode: (v: 'full' | 'profile') => void;
    copyProjects: boolean;
    setCopyProjects: (v: boolean) => void;
    isSettingsModalOpen: boolean;
    setIsSettingsModalOpen: (v: boolean) => void;
    settingsModalTarget: InstanceStatus | null;
    setSettingsModalTarget: (v: InstanceStatus | null) => void;
    editTargetId: string | null;
    setEditTargetId: (v: string | null) => void;
    editInstanceName: string;
    setEditInstanceName: (v: string) => void;
    auditModalInstance: { id: string; name: string; sequence_name?: string } | null;
    setAuditModalInstance: (v: InstancePageApi['auditModalInstance']) => void;
    deleteModalTarget: InstanceStatus | null;
    setDeleteModalTarget: (v: InstanceStatus | null) => void;
    wipeModalTarget: InstanceStatus | null;
    setWipeModalTarget: (v: InstanceStatus | null) => void;
    fetchInstances: (silent?: boolean) => Promise<void>;
    fetchRunningTasks: () => Promise<void>;
    fetchSwitcherStatus: () => Promise<void>;
    handleSetViewMode: (mode: 'card' | 'list') => void;
    handleSetCardDensity: (density: 'normal' | 'compact') => void;
    handleCreate: () => Promise<void>;
    handleInitDefault: () => Promise<void>;
    handleCopy: () => Promise<void>;
    handleEdit: () => Promise<void>;
    handleDelete: (id: string) => void;
    handleConfirmDelete: () => Promise<void>;
    handleWipeSession: (id: string) => void;
    handleConfirmWipe: () => Promise<void>;
    handleLaunch: (id: string) => Promise<void>;
    handleStop: (id: string) => Promise<void>;
    handleRestart: (id: string) => Promise<void>;
    handleFastForward: (id: string) => Promise<void>;
    handleSync: (id: string) => Promise<void>;
    handleCloneExecutable: (id: string) => Promise<void>;
    handleSyncAll: () => Promise<void>;
    handleCleanRestart: () => Promise<void>;
    handleToggleAutoSwitcher: () => Promise<void>;
    handleTriggerRotation: () => Promise<void>;
    openSwitchDialog: (id: string) => void;
    openAuditDialog: (id: string, name: string) => void;
    openSettingsDialog: (id: string) => void;
    openCopyDialog: (id: string, name: string) => void;
    openPromptTree: (id: string) => void;
    setActiveInstance: (id: string) => Promise<void>;
    setDefaultInstance: (id: string) => Promise<void>;
    switchAccountToInstance: (accountId: string, instanceId?: string) => Promise<void>;
    hasActiveTaskFor: (inst: import('../../services/instanceService').InstanceStatus) => boolean;
    refreshQuota: (accountId: string) => Promise<void>;
}
