//! Admin route table, second half: OAuth, logs, stats, system, security, user tokens.
//! (Split from the single admin route table to respect the 500-line file limit.)

use axum::{
    routing::{delete, get, post},
    Router,
};

pub(crate) fn admin_route_table_b() -> Router {
    let admin_routes = Router::new()
        .route(
            "/accounts/oauth/prepare",
            post(admin_oauth::admin_prepare_oauth_url),
        )
        .route(
            "/accounts/oauth/start",
            post(admin_oauth::admin_start_oauth_login),
        )
        .route(
            "/accounts/oauth/complete",
            post(admin_oauth::admin_complete_oauth_login),
        )
        .route(
            "/accounts/oauth/cancel",
            post(admin_oauth::admin_cancel_oauth_login),
        )
        .route(
            "/accounts/oauth/submit-code",
            post(admin_oauth::admin_submit_oauth_code),
        )
        .route(
            "/accounts/oauth/clients",
            get(admin_oauth::admin_list_oauth_clients),
        )
        .route(
            "/accounts/oauth/client",
            get(admin_oauth::admin_get_active_oauth_client)
                .post(admin_oauth::admin_set_active_oauth_client),
        )
        .route(
            "/zai/models/fetch",
            post(admin_logs::admin_fetch_zai_models),
        )
        .route(
            "/proxy/monitor/toggle",
            post(admin_logs::admin_set_proxy_monitor_enabled),
        )
        .route(
            "/proxy/monitor/health-logs/toggle",
            post(admin_proxy::admin_set_proxy_capture_health_logs),
        )
        .route(
            "/proxy/cloudflared/status",
            get(admin_cloudflared::admin_cloudflared_get_status),
        )
        .route(
            "/proxy/cloudflared/install",
            post(admin_cloudflared::admin_cloudflared_install),
        )
        .route(
            "/proxy/cloudflared/start",
            post(admin_cloudflared::admin_cloudflared_start),
        )
        .route(
            "/proxy/cloudflared/stop",
            post(admin_cloudflared::admin_cloudflared_stop),
        )
        .route("/system/open-folder", post(admin_import::admin_open_folder))
        .route("/proxy/stats", get(admin_logs::admin_get_proxy_stats))
        .route("/logs", get(admin_logs::admin_get_proxy_logs_filtered))
        .route(
            "/logs/count",
            get(admin_logs::admin_get_proxy_logs_count_filtered),
        )
        .route("/logs/clear", post(admin_logs::admin_clear_proxy_logs))
        .route(
            "/proxy/thinking-store/clear",
            post(admin_logs::admin_clear_thinking_store),
        )
        .route(
            "/proxy/thinking-store/count",
            get(admin_logs::admin_get_thinking_store_count),
        )
        .route("/logs/:logId", get(admin_logs::admin_get_proxy_log_detail))
        // Debug Console (Log Bridge)
        .route(
            "/debug/enable",
            post(admin_system::admin_enable_debug_console),
        )
        .route(
            "/debug/disable",
            post(admin_system::admin_disable_debug_console),
        )
        .route(
            "/debug/enabled",
            get(admin_system::admin_is_debug_console_enabled),
        )
        .route(
            "/debug/logs",
            get(admin_system::admin_get_debug_console_logs),
        )
        .route(
            "/debug/logs/clear",
            post(admin_system::admin_clear_debug_console_logs),
        )
        .route(
            "/stats/token/clear",
            post(admin_stats::admin_clear_token_stats),
        )
        .route(
            "/stats/token/hourly",
            get(admin_stats::admin_get_token_stats_hourly),
        )
        .route(
            "/stats/token/daily",
            get(admin_stats::admin_get_token_stats_daily),
        )
        .route(
            "/stats/token/weekly",
            get(admin_stats::admin_get_token_stats_weekly),
        )
        .route(
            "/stats/token/by-account",
            get(admin_stats::admin_get_token_stats_by_account),
        )
        .route(
            "/stats/token/summary",
            get(admin_stats::admin_get_token_stats_summary),
        )
        .route(
            "/stats/token/by-model",
            get(admin_stats::admin_get_token_stats_by_model),
        )
        .route(
            "/stats/token/model-trend/hourly",
            get(admin_stats::admin_get_token_stats_model_trend_hourly),
        )
        .route(
            "/stats/token/model-trend/daily",
            get(admin_stats::admin_get_token_stats_model_trend_daily),
        )
        .route(
            "/stats/token/account-trend/hourly",
            get(admin_stats::admin_get_token_stats_account_trend_hourly),
        )
        .route(
            "/stats/token/account-trend/daily",
            get(admin_stats::admin_get_token_stats_account_trend_daily),
        )
        .route(
            "/accounts/bulk-delete",
            post(admin_accounts_ops::admin_delete_accounts),
        )
        .route(
            "/accounts/export",
            post(admin_accounts::admin_export_accounts),
        )
        .route(
            "/accounts/reorder",
            post(admin_accounts_ops::admin_reorder_accounts),
        )
        .route(
            "/accounts/:accountId/quota",
            get(admin_accounts_ops::admin_fetch_account_quota),
        )
        .route(
            "/accounts/:accountId/toggle-proxy",
            post(admin_accounts_ops::admin_toggle_proxy_status),
        )
        .route(
            "/accounts/warmup",
            post(admin_accounts_ops::admin_warm_up_all_accounts),
        )
        .route(
            "/accounts/:accountId/warmup",
            post(admin_accounts_ops::admin_warm_up_account),
        )
        .route(
            "/accounts/:accountId/priority",
            post(admin_accounts_ops::admin_update_account_priority),
        )
        .route(
            "/system/data-dir",
            get(admin_logs::admin_get_data_dir_path).post(admin_logs::admin_set_data_dir),
        )
        .route(
            "/system/updates/settings",
            get(admin_system::admin_get_update_settings),
        )
        .route(
            "/system/updates/check-status",
            get(admin_system::admin_should_check_updates),
        )
        .route(
            "/system/updates/check",
            post(admin_system::admin_check_for_updates),
        )
        .route(
            "/system/updates/touch",
            post(admin_system::admin_update_last_check_time),
        )
        .route(
            "/system/updates/save",
            post(admin_system::admin_save_update_settings),
        )
        .route(
            "/system/autostart/status",
            get(admin_system::admin_is_auto_launch_enabled),
        )
        .route(
            "/system/autostart/toggle",
            post(admin_system::admin_toggle_auto_launch),
        )
        .route(
            "/system/http-api/settings",
            get(admin_system::admin_get_http_api_settings)
                .post(admin_system::admin_save_http_api_settings),
        )
        .route(
            "/system/antigravity/path",
            get(admin_system::admin_get_antigravity_path),
        )
        .route(
            "/system/antigravity/args",
            get(admin_system::admin_get_antigravity_args),
        )
        .route(
            "/system/cache/clear",
            post(admin_system::admin_clear_antigravity_cache),
        )
        .route(
            "/system/cache/paths",
            get(admin_system::admin_get_antigravity_cache_paths),
        )
        .route(
            "/system/logs/clear-cache",
            post(admin_system::admin_clear_log_cache),
        )
        // Security / IP Monitoring
        .route(
            "/security/logs",
            get(admin_security::admin_get_ip_access_logs),
        )
        .route(
            "/security/logs/clear",
            post(admin_security::admin_clear_ip_access_logs),
        )
        .route("/security/stats", get(admin_security::admin_get_ip_stats))
        .route(
            "/security/token-stats",
            get(admin_security::admin_get_ip_token_stats),
        ) // For IP Token usage
        .route(
            "/security/blacklist",
            get(admin_security::admin_get_ip_blacklist)
                .post(admin_security::admin_add_ip_to_blacklist)
                .delete(admin_security::admin_remove_ip_from_blacklist),
        )
        .route(
            "/security/blacklist/clear",
            post(admin_security::admin_clear_ip_blacklist),
        )
        .route(
            "/security/blacklist/check",
            get(admin_security::admin_check_ip_in_blacklist),
        )
        .route(
            "/security/whitelist",
            get(admin_security::admin_get_ip_whitelist)
                .post(admin_security::admin_add_ip_to_whitelist)
                .delete(admin_security::admin_remove_ip_from_whitelist),
        )
        .route(
            "/security/whitelist/clear",
            post(admin_security::admin_clear_ip_whitelist),
        )
        .route(
            "/security/whitelist/check",
            get(admin_security::admin_check_ip_in_whitelist),
        )
        .route(
            "/security/config",
            get(admin_security::admin_get_security_config)
                .post(admin_security::admin_update_security_config),
        )
        // User Tokens
        .route(
            "/user-tokens",
            get(admin_tokens::admin_list_user_tokens).post(admin_tokens::admin_create_user_token),
        )
        .route(
            "/user-tokens/summary",
            get(admin_tokens::admin_get_user_token_summary),
        )
        .route(
            "/user-tokens/:id/renew",
            post(admin_tokens::admin_renew_user_token),
        )
        .route(
            "/user-tokens/:id",
            delete(admin_tokens::admin_delete_user_token)
                .patch(admin_tokens::admin_update_user_token),
        )
        // OAuth (Web) - Admin endpoint
        .route("/auth/url", get(admin_oauth::admin_prepare_oauth_url_web));
    admin_routes
}
