//! Admin route table, first half: health, instances, prompts, accounts, proxy service.
//! (Split from the single admin route table to respect the 500-line file limit.)

use super::router_proxy::health_check_handler;
use axum::{
    routing::{delete, get, post},
    Router,
};

pub(crate) fn admin_route_table_a() -> Router {
    let admin_routes = Router::new()
        .route("/health", get(health_check_handler))
        // ── Instance Management REST Routes ──
        .route(
            "/instances",
            get(admin_instances::admin_list_instances).post(admin_instances::admin_create_instance),
        )
        .route(
            "/instances/:id",
            get(admin_instances::admin_get_instance_detail)
                .delete(admin_instances::admin_delete_instance),
        )
        .route(
            "/instances/:id/status",
            get(admin_instances::admin_get_instance_status),
        )
        .route(
            "/instances/:id/start",
            post(admin_instances::admin_start_instance),
        )
        .route(
            "/instances/:id/stop",
            post(admin_instances::admin_stop_instance),
        )
        .route(
            "/instances/:id/restart",
            post(admin_instances::admin_restart_instance),
        )
        .route(
            "/instances/:id/switch",
            post(admin_instances::admin_switch_instance_account),
        )
        .route(
            "/instances/:id/clone",
            post(admin_instances::admin_clone_instance),
        )
        .route(
            "/instances/:id/logs",
            get(admin_instances::admin_get_instance_logs),
        )
        // ── Prompt Lifecycle REST Routes ──
        .route(
            "/prompts",
            get(admin_prompts::admin_list_prompts).post(admin_prompts::admin_dispatch_prompt),
        )
        .route("/prompts/tree", get(admin_prompts::admin_get_prompt_tree))
        .route(
            "/prompts/running",
            get(admin_prompts::admin_get_running_prompts),
        )
        .route(
            "/prompts/dispatch",
            post(admin_prompts::admin_dispatch_prompt),
        )
        .route(
            "/prompts/queue/tick",
            post(admin_prompts::admin_tick_prompt_queue),
        )
        .route("/prompts/backup", post(admin_prompts::admin_backup_prompts))
        .route(
            "/prompts/restore",
            post(admin_prompts::admin_restore_prompts),
        )
        .route("/prompts/purge", post(admin_prompts::admin_purge_prompts))
        .route("/prompts/:id", get(admin_prompts::admin_get_prompt_detail))
        // ── System Diagnostics REST Routes ──
        .route("/system/db-stats", get(admin_prompts::admin_get_db_stats))
        .route("/system/vacuum", post(admin_prompts::admin_vacuum_system))
        .route(
            "/accounts",
            get(admin_accounts::admin_list_accounts).post(admin_accounts::admin_add_account),
        )
        .route(
            "/accounts/current",
            get(admin_accounts::admin_get_current_account),
        )
        .route(
            "/accounts/switch",
            post(admin_accounts::admin_switch_account),
        )
        .route(
            "/accounts/rotate",
            post(admin_accounts::admin_rotate_account),
        )
        .route(
            "/auto-switcher/rotate",
            post(admin_accounts::admin_rotate_account),
        )
        .route(
            "/auto-switcher/status",
            get(admin_accounts::admin_get_auto_switcher_status),
        )
        .route(
            "/repo-db/projects",
            get(admin_oauth::admin_list_repo_projects),
        )
        .route(
            "/repo-db/prompts",
            get(admin_oauth::admin_list_repo_prompts),
        )
        .route(
            "/accounts/refresh",
            post(admin_oauth::admin_refresh_all_quotas),
        )
        .route(
            "/accounts/:accountId",
            delete(admin_accounts::admin_delete_account),
        )
        .route(
            "/accounts/:accountId/bind-device",
            post(admin_devices::admin_bind_device),
        )
        .route(
            "/accounts/:accountId/device-profiles",
            get(admin_devices::admin_get_device_profiles),
        )
        .route(
            "/accounts/:accountId/device-versions",
            get(admin_devices::admin_list_device_versions),
        )
        .route(
            "/accounts/device-preview",
            post(admin_devices::admin_preview_generate_profile),
        )
        .route(
            "/accounts/:accountId/bind-device-profile",
            post(admin_devices::admin_bind_device_profile_with_profile),
        )
        .route(
            "/accounts/restore-original",
            post(admin_devices::admin_restore_original_device),
        )
        .route(
            "/accounts/:accountId/device-versions/:versionId/restore",
            post(admin_devices::admin_restore_device_version),
        )
        .route(
            "/accounts/:accountId/device-versions/:versionId",
            delete(admin_devices::admin_delete_device_version),
        )
        .route(
            "/accounts/import/v1",
            post(admin_import::admin_import_v1_accounts),
        )
        .route(
            "/accounts/import/db",
            post(admin_import::admin_import_from_db),
        )
        .route(
            "/accounts/import/db-custom",
            post(admin_import::admin_import_custom_db),
        )
        .route(
            "/accounts/sync/db",
            post(admin_import::admin_sync_account_from_db),
        )
        .route(
            "/stats/summary",
            get(admin_stats::admin_get_token_stats_summary),
        )
        .route(
            "/stats/hourly",
            get(admin_stats::admin_get_token_stats_hourly),
        )
        .route(
            "/stats/daily",
            get(admin_stats::admin_get_token_stats_daily),
        )
        .route(
            "/stats/weekly",
            get(admin_stats::admin_get_token_stats_weekly),
        )
        .route(
            "/stats/accounts",
            get(admin_stats::admin_get_token_stats_by_account),
        )
        .route(
            "/stats/models",
            get(admin_stats::admin_get_token_stats_by_model),
        )
        .route(
            "/config",
            get(admin_config::admin_get_config).post(admin_config::admin_save_config),
        )
        .route(
            "/proxy/cli/status",
            post(admin_import::admin_get_cli_sync_status),
        )
        .route(
            "/proxy/cli/sync",
            post(admin_import::admin_execute_cli_sync),
        )
        .route(
            "/proxy/cli/restore",
            post(admin_import::admin_execute_cli_restore),
        )
        .route(
            "/proxy/cli/config",
            post(admin_import::admin_get_cli_config_content),
        )
        .route(
            "/proxy/opencode/status",
            post(admin_sync_opencode::admin_get_opencode_sync_status),
        )
        .route(
            "/proxy/opencode/providers",
            get(admin_sync_opencode::admin_get_opencode_providers),
        )
        .route(
            "/proxy/opencode/sync",
            post(admin_sync_opencode::admin_execute_opencode_sync),
        )
        .route(
            "/proxy/opencode/openai-sync",
            post(admin_sync_opencode::admin_execute_opencode_openai_sync),
        )
        .route(
            "/proxy/opencode/remove-provider",
            post(admin_sync_opencode::admin_execute_opencode_remove_provider),
        )
        .route(
            "/proxy/opencode/restore",
            post(admin_sync_opencode::admin_execute_opencode_restore),
        )
        .route(
            "/proxy/opencode/clear",
            post(admin_sync_opencode::admin_execute_opencode_clear),
        )
        .route(
            "/proxy/opencode/config",
            post(admin_sync_opencode::admin_get_opencode_config_content),
        )
        .route(
            "/proxy/opencode/families",
            get(admin_sync_opencode::admin_get_opencode_families),
        )
        .route(
            "/proxy/hermes/status",
            post(admin_sync_external::admin_get_hermes_sync_status),
        )
        .route(
            "/proxy/hermes/sync",
            post(admin_sync_external::admin_execute_hermes_sync),
        )
        .route(
            "/proxy/hermes/restore",
            post(admin_sync_external::admin_execute_hermes_restore),
        )
        .route(
            "/proxy/hermes/clear",
            post(admin_sync_external::admin_execute_hermes_clear),
        )
        .route(
            "/proxy/hermes/config",
            post(admin_sync_external::admin_get_hermes_config_content),
        )
        .route(
            "/proxy/openclaw/status",
            post(admin_sync_external::admin_get_openclaw_sync_status),
        )
        .route(
            "/proxy/openclaw/sync",
            post(admin_sync_external::admin_execute_openclaw_sync),
        )
        .route(
            "/proxy/openclaw/restore",
            post(admin_sync_external::admin_execute_openclaw_restore),
        )
        .route(
            "/proxy/openclaw/clear",
            post(admin_sync_external::admin_execute_openclaw_clear),
        )
        .route(
            "/proxy/openclaw/config",
            post(admin_sync_external::admin_get_openclaw_config_content),
        )
        .route(
            "/proxy/droid/status",
            post(admin_sync_external::admin_get_droid_sync_status),
        )
        .route(
            "/proxy/droid/sync",
            post(admin_sync_external::admin_execute_droid_sync),
        )
        .route(
            "/proxy/droid/restore",
            post(admin_sync_external::admin_execute_droid_restore),
        )
        .route(
            "/proxy/droid/config",
            post(admin_sync_external::admin_get_droid_config_content),
        )
        .route("/proxy/status", get(admin_proxy::admin_get_proxy_status))
        .route(
            "/proxy/pool/config",
            get(admin_proxy::admin_get_proxy_pool_config),
        )
        .route(
            "/proxy/pool/bindings",
            get(admin_proxy::admin_get_all_account_bindings),
        )
        .route(
            "/proxy/pool/bind",
            post(admin_proxy::admin_bind_account_proxy),
        )
        .route(
            "/proxy/pool/unbind",
            post(admin_proxy::admin_unbind_account_proxy),
        )
        .route(
            "/proxy/pool/binding/:accountId",
            get(admin_proxy::admin_get_account_proxy_binding),
        )
        .route(
            "/proxy/health-check/trigger",
            post(admin_proxy::admin_trigger_proxy_health_check),
        )
        .route("/proxy/start", post(admin_proxy::admin_start_proxy_service))
        .route("/proxy/stop", post(admin_proxy::admin_stop_proxy_service))
        .route(
            "/proxy/mapping",
            post(admin_proxy::admin_update_model_mapping),
        )
        .route(
            "/proxy/api-key/generate",
            post(admin_proxy::admin_generate_api_key),
        )
        .route(
            "/proxy/session-bindings/clear",
            post(admin_proxy::admin_clear_proxy_session_bindings),
        )
        .route(
            "/proxy/rate-limits",
            delete(admin_proxy::admin_clear_all_rate_limits),
        )
        .route(
            "/proxy/rate-limits/:accountId",
            delete(admin_proxy::admin_clear_rate_limit),
        )
        .route(
            "/proxy/preferred-account",
            get(admin_proxy::admin_get_preferred_account)
                .post(admin_proxy::admin_set_preferred_account),
        );
    admin_routes
}
