import { Gemini, Claude, OpenAI, DeepSeek, Qwen, Meta } from '@lobehub/icons';
import type { ModelConfig } from './types';

export const MODEL_CONFIG: Record<string, ModelConfig> = {
    // Gemini 3.x 系列
    'gemini-3.8-flash': {
        label: 'Gemini 3.8 Flash',
        shortLabel: 'G3.8 Flash',
        protectedKey: 'gemini-flash',
        Icon: Gemini.Color,
        i18nKey: 'proxy.model.flash_preview',
        i18nDescKey: 'proxy.model.flash_preview',
        group: 'Gemini 3',
        tags: ['flash'],
        priority: 10,
        capabilities: ['chat', 'fast'],
        speed: 'fast',
    },

    'gemini-3.8-flash-tiered': {
        label: 'Gemini 3.8 Flash',
        shortLabel: 'G3.8 Flash',
        protectedKey: 'gemini-flash',
        Icon: Gemini.Color,
        i18nKey: 'proxy.model.flash_preview',
        i18nDescKey: 'proxy.model.flash_preview',
        group: 'Gemini 3',
        tags: ['flash', 'tiered'],
        priority: 11,
        capabilities: ['chat', 'fast'],
        speed: 'fast',
    },

    'gemini-3.8-flash-high': {
        label: 'Gemini 3.8 Flash (High)',
        shortLabel: 'G3.8 High',
        protectedKey: 'gemini-flash',
        Icon: Gemini.Color,
        i18nKey: 'proxy.model.flash_preview',
        i18nDescKey: 'proxy.model.flash_preview',
        group: 'Gemini 3',
        tags: ['flash', 'high'],
        priority: 12,
        capabilities: ['chat', 'reasoning', 'fast'],
        speed: 'fast',
    },

    'gemini-3.8-flash-medium': {
        label: 'Gemini 3.8 Flash (Medium)',
        shortLabel: 'G3.8 Med',
        protectedKey: 'gemini-flash',
        Icon: Gemini.Color,
        i18nKey: 'proxy.model.flash_preview',
        i18nDescKey: 'proxy.model.flash_preview',
        group: 'Gemini 3',
        tags: ['flash', 'medium'],
        priority: 13,
        capabilities: ['chat', 'fast'],
        speed: 'fast',
    },

    'gemini-3.8-flash-low': {
        label: 'Gemini 3.8 Flash (Low)',
        shortLabel: 'G3.8 Low',
        protectedKey: 'gemini-flash',
        Icon: Gemini.Color,
        i18nKey: 'proxy.model.flash_preview',
        i18nDescKey: 'proxy.model.flash_preview',
        group: 'Gemini 3',
        tags: ['flash', 'low'],
        priority: 14,
        capabilities: ['chat', 'fast'],
        speed: 'fast',
    },

    'gemini-3.7-flash-high': {
        label: 'Gemini 3.7 Flash (High)',
        shortLabel: 'G3.7 High',
        protectedKey: 'gemini-flash',
        Icon: Gemini.Color,
        i18nKey: 'proxy.model.flash_preview',
        i18nDescKey: 'proxy.model.flash_preview',
        group: 'Gemini 3',
        tags: ['flash', 'high'],
        priority: 20,
        capabilities: ['chat', 'reasoning', 'fast'],
        speed: 'fast',
    },

    'gemini-3.7-flash-medium': {
        label: 'Gemini 3.7 Flash (Medium)',
        shortLabel: 'G3.7 Med',
        protectedKey: 'gemini-flash',
        Icon: Gemini.Color,
        i18nKey: 'proxy.model.flash_preview',
        i18nDescKey: 'proxy.model.flash_preview',
        group: 'Gemini 3',
        tags: ['flash', 'medium'],
        priority: 21,
        capabilities: ['chat', 'fast'],
        speed: 'fast',
    },

    'gemini-3.7-flash-low': {
        label: 'Gemini 3.7 Flash (Low)',
        shortLabel: 'G3.7 Low',
        protectedKey: 'gemini-flash',
        Icon: Gemini.Color,
        i18nKey: 'proxy.model.flash_preview',
        i18nDescKey: 'proxy.model.flash_preview',
        group: 'Gemini 3',
        tags: ['flash', 'low'],
        priority: 22,
        capabilities: ['chat', 'fast'],
        speed: 'fast',
    },

    'gemini-3.7-flash-tiered': {
        label: 'Gemini 3.7 Flash (Tiered)',
        shortLabel: 'G3.7 Tiered',
        protectedKey: 'gemini-flash',
        Icon: Gemini.Color,
        i18nKey: 'proxy.model.flash_preview',
        i18nDescKey: 'proxy.model.flash_preview',
        group: 'Gemini 3',
        tags: ['flash', 'tiered'],
        priority: 23,
        capabilities: ['chat', 'fast'],
        speed: 'fast',
    },

    'gemini-3.1-pro-high': {
        label: 'Gemini 3.1 Pro High',
        shortLabel: 'G3.1 Pro',
        protectedKey: 'gemini-pro',
        Icon: Gemini.Color,
        i18nKey: 'proxy.model.pro_high',
        i18nDescKey: 'proxy.model.pro_high',
        group: 'Gemini 3',
        tags: ['pro', 'high'],
        priority: 30,
        capabilities: ['chat', 'reasoning', 'code'],
        speed: 'balanced',
    },

    'gemini-3-flash': {
        label: 'Gemini 3 Flash',
        shortLabel: 'G3 Flash',
        protectedKey: 'gemini-flash',
        Icon: Gemini.Color,
        i18nKey: 'proxy.model.flash_preview',
        i18nDescKey: 'proxy.model.flash_preview',
        group: 'Gemini 3',
        tags: ['flash'],
        priority: 40,
        capabilities: ['chat', 'fast'],
        speed: 'fast',
    },

    'gemini-3.1-flash-image': {
        label: 'Gemini 3.1 Flash Image',
        shortLabel: 'G3.1 Image',
        protectedKey: 'gemini-3.1-flash-image',
        Icon: Gemini.Color,
        i18nKey: 'proxy.model.pro_image',
        i18nDescKey: 'proxy.model.pro_image_1_1',
        group: 'Gemini 3',
        tags: ['image', 'flash'],
        priority: 70,
        capabilities: ['image', 'vision'],
        speed: 'balanced',
    },

    'gemini-3-pro-image': {
        label: 'Gemini 3 Image',
        shortLabel: 'G3 Image',
        protectedKey: 'gemini-3-pro-image',
        Icon: Gemini.Color,
        i18nKey: 'proxy.model.pro_image',
        i18nDescKey: 'proxy.model.pro_image_1_1',
        group: 'Gemini 3',
        tags: ['image'],
        priority: 71,
        capabilities: ['image', 'vision'],
        speed: 'balanced',
    },

    'gemini-3.5-flash': {
        label: 'Gemini 3.5 Flash',
        shortLabel: 'G3.5 Flash',
        protectedKey: 'gemini-flash',
        Icon: Gemini.Color,
        i18nKey: 'proxy.model.flash_preview',
        i18nDescKey: 'proxy.model.flash_preview',
        group: 'Gemini 3',
        tags: ['flash'],
        priority: 41,
        capabilities: ['chat', 'fast'],
        speed: 'fast',
    },

    'gemini-3.7-flash': {
        label: 'Gemini 3.7 Flash',
        shortLabel: 'G3.7 Flash',
        protectedKey: 'gemini-flash',
        Icon: Gemini.Color,
        i18nKey: 'proxy.model.flash_preview',
        i18nDescKey: 'proxy.model.flash_preview',
        group: 'Gemini 3',
        tags: ['flash'],
        priority: 24,
        capabilities: ['chat', 'fast'],
        speed: 'fast',
    },

    'gemini-3.1-flash-lite': {
        label: 'Gemini 3.1 Flash Lite',
        shortLabel: 'G3.1 Lite',
        protectedKey: 'gemini-flash',
        Icon: Gemini.Color,
        i18nKey: 'proxy.model.flash_lite',
        i18nDescKey: 'proxy.model.flash_lite',
        group: 'Gemini 3',
        tags: ['flash', 'lite'],
        priority: 90,
        capabilities: ['chat', 'fast'],
        speed: 'nano',
    },

    'gemini-3.1-pro': {
        label: 'Gemini 3.1 Pro',
        shortLabel: 'G3.1 Pro',
        protectedKey: 'gemini-pro',
        Icon: Gemini.Color,
        i18nKey: 'proxy.model.pro_high',
        i18nDescKey: 'proxy.model.pro_high',
        group: 'Gemini 3',
        tags: ['pro'],
        priority: 32,
        capabilities: ['chat', 'reasoning', 'code'],
        speed: 'balanced',
    },

    'gemini-3-flash-agent': {
        label: 'Gemini 3.5 Flash (High)',
        shortLabel: 'G3.5 Flash',
        protectedKey: 'gemini-flash',
        Icon: Gemini.Color,
        i18nKey: 'proxy.model.flash_preview',
        i18nDescKey: 'proxy.model.flash_preview',
        group: 'Gemini 3',
        tags: ['flash', 'high'],
        priority: 42,
        capabilities: ['chat', 'agent', 'fast'],
        speed: 'fast',
    },

    'gemini-pro-agent': {
        label: 'Gemini 3.1 Pro (High)',
        shortLabel: 'G3.1 Pro',
        protectedKey: 'gemini-pro',
        Icon: Gemini.Color,
        i18nKey: 'proxy.model.pro_high',
        i18nDescKey: 'proxy.model.pro_high',
        group: 'Gemini 3',
        tags: ['pro', 'high'],
        priority: 31,
        capabilities: ['chat', 'reasoning', 'code', 'agent'],
        speed: 'balanced',
    },

    'gemini-3.1-pro-low': {
        label: 'Gemini 3.1 Pro Low',
        shortLabel: 'G3.1 Low',
        protectedKey: 'gemini-pro',
        Icon: Gemini.Color,
        i18nKey: 'proxy.model.pro_low',
        i18nDescKey: 'proxy.model.pro_low',
        group: 'Gemini 3',
        tags: ['pro', 'low'],
        priority: 33,
        capabilities: ['chat', 'code'],
        speed: 'balanced',
    },



    // Claude 系列
    'claude-sonnet-4-6': {
        label: 'Claude 4.6',
        shortLabel: 'Claude 4.6',
        protectedKey: 'claude',
        Icon: Claude.Color,
        i18nKey: 'proxy.model.claude_sonnet',
        i18nDescKey: 'proxy.model.claude_sonnet',
        group: 'Claude',
        tags: ['sonnet'],
        priority: 50,
        capabilities: ['chat', 'reasoning', 'code'],
        speed: 'balanced',
    },

    'claude-sonnet-4-6-thinking': {
        label: 'Claude 4.6 TK',
        shortLabel: 'Claude 4.6 TK',
        protectedKey: 'claude',
        Icon: Claude.Color,
        i18nKey: 'proxy.model.claude_sonnet_thinking',
        i18nDescKey: 'proxy.model.claude_sonnet_thinking',
        group: 'Claude',
        tags: ['sonnet', 'thinking'],
        priority: 53,
        capabilities: ['chat', 'reasoning', 'code'],
        speed: 'balanced',
    },

    'claude-opus-4-6': {
        label: 'Claude Opus 4.6',
        shortLabel: 'Claude Opus 4.6',
        protectedKey: 'claude',
        Icon: Claude.Color,
        i18nKey: 'proxy.model.claude_opus',
        i18nDescKey: 'proxy.model.claude_opus',
        group: 'Claude',
        tags: ['opus'],
        priority: 52,
        capabilities: ['chat', 'reasoning', 'code'],
        speed: 'powerful',
    },

    'claude-opus-4-6-thinking': {
        label: 'Claude Opus 4.6 TK',
        shortLabel: 'Claude Opus 4.6 TK',
        protectedKey: 'claude',
        Icon: Claude.Color,
        i18nKey: 'proxy.model.claude_opus_thinking',
        i18nDescKey: 'proxy.model.claude_opus_thinking',
        group: 'Claude',
        tags: ['opus', 'thinking'],
        priority: 51,
        capabilities: ['chat', 'reasoning', 'code'],
        speed: 'powerful',
    },


    // OpenAI / Outros modelos
    'gpt-oss-120b-medium': {
        label: 'GPT-OSS 120B (Medium)',
        shortLabel: 'GPT-OSS',
        protectedKey: 'gpt-oss',
        Icon: OpenAI.Avatar,
        i18nKey: 'proxy.model.gpt_oss',
        i18nDescKey: 'proxy.model.gpt_oss',
        group: 'Other',
        tags: ['openai'],
        priority: 60,
        capabilities: ['chat', 'reasoning', 'code'],
        speed: 'balanced',
    },
    // Open Source 系列 (newer open-source models)
    'gpt-oss-20b': {
        label: 'GPT-OSS 20B',
        shortLabel: 'GPT-OSS 20B',
        protectedKey: 'gpt-oss',
        Icon: OpenAI.Avatar,
        i18nKey: 'proxy.model.gpt_oss',
        i18nDescKey: 'proxy.model.gpt_oss',
        group: 'Open Source',
        tags: ['openai', 'open-source', 'small'],
        priority: 91,
        capabilities: ['chat', 'fast', 'code'],
        speed: 'nano',
    },
    'deepseek-v4': {
        label: 'DeepSeek V4',
        shortLabel: 'DeepSeek V4',
        protectedKey: 'deepseek',
        Icon: DeepSeek.Color,
        i18nKey: 'proxy.model.deepseek',
        i18nDescKey: 'proxy.model.deepseek',
        group: 'Open Source',
        tags: ['open-source', 'reasoning'],
        priority: 61,
        capabilities: ['reasoning', 'code', 'chat'],
        speed: 'balanced',
    },
    'qwen3-max': {
        label: 'Qwen3 Max',
        shortLabel: 'Qwen3 Max',
        protectedKey: 'qwen',
        Icon: Qwen.Color,
        i18nKey: 'proxy.model.qwen',
        i18nDescKey: 'proxy.model.qwen',
        group: 'Open Source',
        tags: ['open-source', 'flagship'],
        priority: 62,
        capabilities: ['chat', 'code', 'reasoning'],
        speed: 'balanced',
    },
    'qwen3-8b': {
        label: 'Qwen3 8B',
        shortLabel: 'Qwen3 8B',
        protectedKey: 'qwen',
        Icon: Qwen.Color,
        i18nKey: 'proxy.model.qwen',
        i18nDescKey: 'proxy.model.qwen',
        group: 'Open Source',
        tags: ['open-source', 'small'],
        priority: 92,
        capabilities: ['chat', 'fast'],
        speed: 'nano',
    },
    'llama-4-maverick': {
        label: 'Llama 4 Maverick',
        shortLabel: 'Llama 4',
        protectedKey: 'llama',
        Icon: Meta.Color,
        i18nKey: 'proxy.model.llama',
        i18nDescKey: 'proxy.model.llama',
        group: 'Open Source',
        tags: ['open-source', 'multimodal'],
        priority: 63,
        capabilities: ['chat', 'vision', 'code'],
        speed: 'balanced',
    },

};
